# Generated by Django 3.2.5 on 2022-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_mptt_upgrade'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionversion',
            name='categories',
            field=models.ManyToManyField(blank=True, to='wiki.Article'),
        ),
    ]
