# Generated by Django 3.2.5 on 2022-10-19 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_questionversion_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='question_version',
        ),
        migrations.AddField(
            model_name='submission',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
