# Generated by Django 3.2.5 on 2022-10-26 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0005_alter_urlpath_slug'),
        ('core', '0005_auto_20221025_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='slug',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='wiki.article'),
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='description',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionversion',
            name='title',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
