# Generated by Django 3.2.5 on 2022-11-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221026_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionversion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='AnswerVersion',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionVersion',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
