# Generated by Django 3.2.5 on 2023-01-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_message',
            field=models.TextField(blank=True, null=True, verbose_name='Nachricht an Benutzer'),
        ),
    ]
