# Generated by Django 3.2.5 on 2023-01-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_submission_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
