# Generated by Django 3.2.5 on 2022-11-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionversion',
            name='approved',
        ),
        migrations.AddField(
            model_name='question',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
