# Generated by Django 3.2.5 on 2022-11-22 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20221122_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='current',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_version', to='quiz.questionversion'),
        ),
    ]
