# Generated by Django 3.2.5 on 2023-01-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_current'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionversion',
            options={'verbose_name': 'MCT Frage'},
        ),
    ]
