# Generated by Django 3.2.4 on 2021-06-24 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0001_initial'),
        ('wagtailimages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTable',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormerPeopleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PeopleIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='SessionIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('date', wagtail.core.fields.RichTextField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('lecture', 'Vorlesung'), ('exercise', 'Übung'), ('study_group', 'Arbeitsgemeinschaft'), ('exam_prep', 'Klausurenkurs'), ('seminar', 'Seminar')], default='lecture', max_length=255)),
                ('semester', models.CharField(blank=True, choices=[('ss2022', 'Sommersemester 2022'), ('ws2022', 'Wintersemester 2022'), ('ss2021', 'Sommersemester 2021'), ('ws2021', 'Wintersemester 2021'), ('ss2020', 'Sommersemester 2020'), ('ws2020', 'Wintersemester 2020'), ('ss2019', 'Sommersemester 2019'), ('ws2019', 'Wintersemester 2019'), ('ss2018', 'Sommersemester 2018'), ('ws2018', 'Wintersemester 2018')], default='ws2020', max_length=255)),
                ('assessment', wagtail.core.fields.RichTextField(blank=True)),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('speaker_description', wagtail.core.fields.RichTextField(blank=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True)),
                ('location', wagtail.core.fields.RichTextField(blank=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lehrveranstaltung',
                'verbose_name_plural': 'Lehrveranstaltungen',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=255, verbose_name='Nachname')),
                ('status', models.CharField(blank=True, choices=[('former', 'Ehemalig'), ('current', 'Aktuell')], default='former', max_length=255)),
                ('role', models.CharField(blank=True, choices=[('chairholder', 'Lehstuhlinhaber'), ('office-management', 'Office Management'), ('academic-staff-male', 'Wiss. Mitarbeiter'), ('academic-staff-female', 'Wiss. Mitarbeiterin'), ('former academic-staff-male', 'Ehem. Wiss. Mitarbeiter'), ('former academic-staff-female', 'Ehem. Wissenschaftliche Mitarbeiterin'), ('academic-assistant', 'Wiss. Hilfskraft'), ('student-assistant', 'Stud. Hilfskraft'), ('jurcoach-law-team-academic', 'Wiss. Hilfskraft Jurcoach'), ('jurcoach-law-team-student', 'Stud. Hilfskraft Jurcoach'), ('jurcoach-evaluation-team', 'Jurcoach Evaluations-Team'), ('jurcoach-web-team', 'Jurcoach Informatik-Team'), ('webmaster', 'Webmaster'), ('associate-professor', 'Privatdozent')], max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255, verbose_name='Telefonnummer')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Mailadresse')),
                ('room', models.CharField(blank=True, max_length=255, verbose_name='Raumnummer')),
                ('description', wagtail.core.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Personen',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='events',
            name='poster_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
