# Generated by Django 3.1.8 on 2021-07-09 14:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailmenus', '0023_remove_use_specific'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('pages', '0010_auto_20210709_1419'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsNewsletterPage',
            new_name='NewslettersPage',
        ),
    ]
