# Generated by Django 3.2.5 on 2021-08-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_eventpage_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpage',
            options={},
        ),
        migrations.RenameField(
            model_name='sessionpage',
            old_name='content',
            new_name='material',
        ),
    ]
