# Generated by Django 3.2.5 on 2021-10-21 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_color_panel.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtaildocs', '0012_uploadeddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailpolls', '0001_initial'),
        ('pages', '0025_auto_20211014_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlepage',
            options={'verbose_name': 'News-Artikel', 'verbose_name_plural': 'News-Artikel'},
        ),
        migrations.AlterModelOptions(
            name='articlespage',
            options={'verbose_name': 'News-Index-Seite', 'verbose_name_plural': 'News-Index-Seiten'},
        ),
        migrations.AlterModelOptions(
            name='evaluationspage',
            options={'verbose_name': 'Abstimmungen-Index-Seite', 'verbose_name_plural': 'Abstimmungen-Index-Seiten'},
        ),
        migrations.AlterModelOptions(
            name='eventpage',
            options={'verbose_name': 'Event-Seite', 'verbose_name_plural': 'Event-Seiten'},
        ),
        migrations.AlterModelOptions(
            name='eventspage',
            options={'verbose_name': 'Event-Index-Seite'},
        ),
        migrations.AlterModelOptions(
            name='examtable',
            options={'verbose_name': 'Klausurdatenbank-Seite'},
        ),
        migrations.AlterModelOptions(
            name='formerpeopleindexpage',
            options={'verbose_name': 'Ehemalige Mitarbeiter*innen-Seite'},
        ),
        migrations.AlterModelOptions(
            name='genericpage',
            options={'verbose_name': 'Generische Seite'},
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Startseite'},
        ),
        migrations.AlterModelOptions(
            name='jurcoachpage',
            options={'verbose_name': 'Jurcoach-Startseite'},
        ),
        migrations.AlterModelOptions(
            name='newsletterspage',
            options={'verbose_name': 'Newsletter-Seite', 'verbose_name_plural': 'Newsletter-Seiten'},
        ),
        migrations.AlterModelOptions(
            name='peopleindexpage',
            options={'verbose_name': 'Aktuelle Mitarbeiter*innen-Seite'},
        ),
        migrations.AlterModelOptions(
            name='sessionpage',
            options={'verbose_name': 'Lehrveranstaltung', 'verbose_name_plural': 'Lehrveranstaltungen'},
        ),
        migrations.AlterModelOptions(
            name='sessionspage',
            options={'verbose_name': 'Lehre-Seite', 'verbose_name_plural': 'Lehre-Seiten'},
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Autor*in'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='News-Artikel-Text'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='is_evaluation',
            field=models.BooleanField(default=False, verbose_name='Handelt es sich um eine Abstimmungsauswertung?'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung'))], blank=True, verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='articlespage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('article_list_block', wagtail.core.blocks.StructBlock([], label='Auflistung aller News-Artikel')), ('evaluation_list_block', wagtail.core.blocks.StructBlock([], label='Auflistung aller Abstimmungsauswertungen'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='articlespage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung'))], verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='evaluationspage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('evaluation_list_block', wagtail.core.blocks.StructBlock([], label='Auflistung aller Abstimmungsauswertungen'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='evaluationspage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar', wagtail.core.blocks.StreamBlock([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung'))], label='Seitenleiste', required=False))], verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date',
            field=models.DateTimeField(verbose_name='Datum (die hier eingetragene Uhrzeit muss nicht stimmen)'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Vortragsankündidungstext'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Link zum Newsletter, sofern es einen Event-Bericht gab'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='poster_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Plakat als Bilddatei'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='poster_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='Plakat als PDF-Datei'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='semester',
            field=models.CharField(blank=True, choices=[('ws-2024', 'Wintersemester 2024/2025'), ('sos-2024', 'Sommersemester 2024'), ('ws-2023', 'Wintersemester 2023/2024'), ('sos-2023', 'Sommersemester 2023'), ('ws-2022', 'Wintersemester 2022/2023'), ('sos-2022', 'Sommersemester 2022'), ('ws-2021', 'Wintersemester 2021/2022'), ('sos-2021', 'Sommersemester 2021'), ('ws-2020', 'Wintersemester 2020/2021'), ('sos-2020', 'Sommersemester 2020'), ('ws-2019', 'Wintersemester 2019/2020'), ('sos-2019', 'Sommersemester 2019'), ('ws-2018', 'Wintersemester 2018/2019'), ('sos-2018', 'Sommersemester 2018'), ('ws-2017', 'Wintersemester 2017/2018'), ('sos-2017', 'Sommersemester 2017'), ('ws-2016', 'Wintersemester 2016/2017'), ('sos-2016', 'Sommersemester 2016'), ('ws-2015', 'Wintersemester 2015/2016'), ('sos-2015', 'Sommersemester 2015'), ('ws-2014', 'Wintersemester 2014/2015'), ('sos-2014', 'Sommersemester 2014'), ('ws-2013', 'Wintersemester 2013/2014'), ('sos-2013', 'Sommersemester 2013'), ('ws-2012', 'Wintersemester 2012/2013'), ('sos-2012', 'Sommersemester 2012'), ('ws-2011', 'Wintersemester 2011/2012'), ('sos-2011', 'Sommersemester 2011'), ('ws-2010', 'Wintersemester 2010/2011'), ('sos-2010', 'Sommersemester 2010')], max_length=255, verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='showmap',
            field=models.BooleanField(default=False, verbose_name='Soll eine Karte auf der Event-Seite angezeigt werden?'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='speaker_description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Referent*in'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Untertitel'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='type',
            field=models.CharField(blank=True, choices=[('tacheles', 'Tacheles'), ('sonstige', 'Sonstige')], default='tacheles', max_length=255, verbose_name='Tacheles-Vortrag oder was anderes?'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link zur Aufzeichnung des Vortrags auf YouTube'),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('events_block', wagtail.core.blocks.StructBlock([], label='Auflistung aller Tacheles-Events nach Semestern'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('color', wagtail_color_panel.blocks.NativeColorBlock('color', default='#333d44')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False))], label='Bild oben, Text darunter')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts'))], blank=True, verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Anfänger'), ('intermediate', 'Fortgeschrittene'), ('advanced', 'Examen')], max_length=255, verbose_name='Schwierigkeitsgrad'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='loesung_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link zur Lösungsskizze'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='paragraphs',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Paragraphen/Strafbarkeiten in der Klausur'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='problems',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Problemschwerpunkte der Klausur'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='sachverhalt_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link zum Sachverhalt'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='type',
            field=models.CharField(blank=True, choices=[('falltraining', 'Klausur im Falltraining'), ('exam', 'Examensklausur'), ('original-exam', 'Originalexamensklausur'), ('exercise', 'Übungsfall'), ('tutorial', 'AG-Fall')], max_length=255, verbose_name='Klausurtyp'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('home_news_block', wagtail.core.blocks.StructBlock([], label='Vier letzte News-Beiträge')), ('home_jurcoach_block', wagtail.core.blocks.StructBlock([], label='Jurcoach-Startseiten-Widget'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Graffito-Bild im Header'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar', wagtail.core.blocks.StreamBlock([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts')), ('sidebar_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('color', wagtail_color_panel.blocks.NativeColorBlock('color', default='#333d44')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False))], label='Bild oben, Text darunter')), ('sidebar_calendar_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('calendar', wagtail.core.blocks.DateBlock(format='%Y-%m-%d'))], label='Kalender links, Text rechts')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung')), ('sidebar_subscribe', wagtail.core.blocks.StructBlock([])), ('sidebar_event', wagtail.core.blocks.StructBlock([]))], label='Seitenleiste', required=False))], verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('home_news_block', wagtail.core.blocks.StructBlock([], label='Vier letzte News-Beiträge')), ('home_jurcoach_block', wagtail.core.blocks.StructBlock([], label='Jurcoach-Startseiten-Widget'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Graffito-Bild im Header'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar', wagtail.core.blocks.StreamBlock([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts')), ('sidebar_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('color', wagtail_color_panel.blocks.NativeColorBlock('color', default='#333d44')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False))], label='Bild oben, Text darunter')), ('sidebar_calendar_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('calendar', wagtail.core.blocks.DateBlock(format='%Y-%m-%d'))], label='Kalender links, Text rechts')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung')), ('sidebar_subscribe', wagtail.core.blocks.StructBlock([])), ('sidebar_event', wagtail.core.blocks.StructBlock([]))], label='Seitenleiste', required=False))], verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='jurcoachcarousel',
            name='carousel_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='jurcoachcarousel',
            name='carousel_link_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Verlinkter Text'),
        ),
        migrations.AlterField(
            model_name='jurcoachcarousel',
            name='carousel_link_url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='jurcoachcarousel',
            name='illustration',
            field=models.CharField(blank=True, choices=[('falltraining', 'Falltraining'), ('wiki', 'Problemfeld-Wiki'), ('mct', 'Multiple-Choice-Test'), ('klausurdatenbank', 'Klausurdatenbank'), ('rechtsprechung', 'Höchstrichterliche Rechtsprechung')], max_length=255, verbose_name='Auswahl der Illustration'),
        ),
        migrations.AlterField(
            model_name='jurcoachfooter',
            name='footeritem_headline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Überschrift'),
        ),
        migrations.AlterField(
            model_name='jurcoachfooter',
            name='footeritem_linktext',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Verlinkter Text'),
        ),
        migrations.AlterField(
            model_name='jurcoachfooter',
            name='footeritem_linkurl',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='jurcoachfooter',
            name='footeritem_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='carousel_headline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Slider-Überschrift'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='contribution_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Mitmachfunktionen-Beschreibung'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='contribution_headline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mitmachfunktionen-Überschrift'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Graffito-Bild im Header'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='header_headline',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Mit Graffito unterlegte Überschrift'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='header_slogan',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Mit Graffito unterlegter Untertitel'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='intro_headline',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Intro-Überschrift'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='intro_text',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Intro-Text'),
        ),
        migrations.AlterField(
            model_name='jurcoachpage',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailpolls.poll', verbose_name='Abstimmung'),
        ),
        migrations.AlterField(
            model_name='newsletterspage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='newsletterspage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar', wagtail.core.blocks.StreamBlock([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung'))], label='Seitenleiste', required=False))], verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='people',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Beschreibung/Weitere Informationen'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Profilbild'),
        ),
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.CharField(blank=True, choices=[('chairholder', 'Lehstuhlinhaber'), ('office-management', 'Office Management'), ('academic-staff-male', 'Wiss. Mitarbeiter'), ('academic-staff-female', 'Wiss. Mitarbeiterin'), ('academic-assistant', 'Wiss. Hilfskraft'), ('student-assistant', 'Stud. Hilfskraft'), ('jurcoach-law-team', 'Jurcoach Jura-Team'), ('jurcoach-evaluation-team', 'Jurcoach Evaluations-Team'), ('jurcoach-web-team', 'Jurcoach Informatik-Team'), ('webmaster', 'Webmaster'), ('associate-professor', 'Privatdozent')], max_length=255, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='people',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verknüpfung mit Nutzer*innen-Account'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='assessment',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Datum/Zeit'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='date',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Datum/Zeit'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Veranstaltungsbeschreibung'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='location',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Längengrad'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='material',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Materialien'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='semester',
            field=models.CharField(blank=True, choices=[('ss-2022', 'Sommersemester 2022'), ('ws-2022', 'Wintersemester 2022'), ('ss-2021', 'Sommersemester 2021'), ('ws-2021', 'Wintersemester 2021'), ('ss-2020', 'Sommersemester 2020'), ('ws-2020', 'Wintersemester 2020'), ('ss-2019', 'Sommersemester 2019'), ('ws-2019', 'Wintersemester 2019'), ('ss-2018', 'Sommersemester 2018'), ('ws-2018', 'Sommersemester 2018'), ('ss-2017', 'Sommersemester 2017'), ('ws-2017', 'Wintersemester 2017'), ('ss-2016', 'Sommersemester 2016'), ('ws-2016', 'Wintersemester 2015'), ('ss-2015', 'Sommersemester 2015'), ('ws-2015', 'Wintersemester 2014'), ('ss-2014', 'Sommersemester 2014'), ('ws-2014', 'Wintersemester 2014'), ('ss-2013', 'Sommersemester 2013'), ('ws-2013', 'Wintersemester 2013'), ('ss-2012', 'Sommersemester 2012'), ('ws-2012', 'Wintersemester 2012'), ('ss-2011', 'Sommersemester 2011'), ('ws-2011', 'Wintersemester 2011'), ('ss-2010', 'Sommersemester 2010'), ('ws-2010', 'Wintersemester 2010'), ('ss-2009', 'Sommersemester 2009'), ('ws-2009', 'Wintersemester 2009'), ('ss-2008', 'Sommersemester 2008'), ('ws-2008', 'Wintersemester 2008'), ('ss-2007', 'Sommersemester 2007'), ('ws-2007', 'Wintersemester 2007'), ('ss-2006', 'Sommersemester 2006'), ('ws-2006', 'Wintersemester 2006'), ('ss-2005', 'Sommersemester 2005'), ('ws-2005', 'Wintersemester 2005'), ('ss-2004', 'Sommersemester 2004'), ('ws-2004', 'Wintersemester 2004')], max_length=255, verbose_name='Semesterauswahl'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('color', wagtail_color_panel.blocks.NativeColorBlock('color', default='#333d44')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False))], label='Bild oben, Text darunter')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts'))], blank=True, verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Dozent*in'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='speaker_description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Beschreibung des*der Dozent*in'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='subtitle',
            field=models.CharField(max_length=255, verbose_name='Untertitel'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='type',
            field=models.CharField(blank=True, choices=[('lecture', 'Vorlesung'), ('exercise', 'Übung'), ('study_group', 'Arbeitsgemeinschaft'), ('exam_prep', 'Klausurenkurs'), ('seminar', 'Seminar')], default='lecture', max_length=255, verbose_name='Veranstaltungstyp'),
        ),
        migrations.AlterField(
            model_name='sessionspage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('semester_block', wagtail.core.blocks.StructBlock([('semester', wagtail.core.blocks.ChoiceBlock(choices=[('ss-2022', 'Sommersemester 2022'), ('ws-2022', 'Wintersemester 2022'), ('ss-2021', 'Sommersemester 2021'), ('ws-2021', 'Wintersemester 2021'), ('ss-2020', 'Sommersemester 2020'), ('ws-2020', 'Wintersemester 2020'), ('ss-2019', 'Sommersemester 2019'), ('ws-2019', 'Wintersemester 2019'), ('ss-2018', 'Sommersemester 2018'), ('ws-2018', 'Wintersemester 2018')], icon='calendar'))], label='Auflistung der Lehrveranstaltungen für ein bestimmtes Semester'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='sessionspage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('color', wagtail_color_panel.blocks.NativeColorBlock('color', default='#333d44')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False))], label='Bild oben, Text darunter')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts'))], blank=True, verbose_name='Seitenleiste'),
        ),
    ]
