# Generated by Django 3.2.5 on 2022-09-27 09:59

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_alter_sessionpage_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericpage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('collapse_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=True)), ('content', wagtail.core.blocks.RichTextBlock(label='Formatierter Text'))], label='Ausklappbares Element')), ('flipcard_block', wagtail.core.blocks.StructBlock([('front', wagtail.core.blocks.RichTextBlock(label='Vorderseite')), ('back', wagtail.core.blocks.RichTextBlock(label='Rückseite'))], label='Flipcard')), ('home_news_block', wagtail.core.blocks.StructBlock([], label='Vier letzte News-Beiträge')), ('home_jurcoach_block', wagtail.core.blocks.StructBlock([], label='Jurcoach-Startseiten-Widget'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StreamBlock([('richtext', wagtail.core.blocks.RichTextBlock(label='Formatierter Text')), ('collapse_block', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=True)), ('content', wagtail.core.blocks.RichTextBlock(label='Formatierter Text'))], label='Ausklappbares Element')), ('flipcard_block', wagtail.core.blocks.StructBlock([('front', wagtail.core.blocks.RichTextBlock(label='Vorderseite')), ('back', wagtail.core.blocks.RichTextBlock(label='Rückseite'))], label='Flipcard')), ('home_news_block', wagtail.core.blocks.StructBlock([], label='Vier letzte News-Beiträge')), ('home_jurcoach_block', wagtail.core.blocks.StructBlock([], label='Jurcoach-Startseiten-Widget'))], label='Hauptspalte'))], verbose_name='Hauptspalte'),
        ),
    ]
