# Generated by Django 3.2.5 on 2022-11-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20221121_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='allow_comments',
            field=models.BooleanField(default=False, verbose_name='Kommentare einschalten?'),
        ),
    ]
