# Generated by Django 3.2.5 on 2022-11-25 17:41

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_articlepage_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='allow_comments',
            field=models.BooleanField(default=False, verbose_name='Kommentare erlaubt'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='allow_comments',
            field=models.BooleanField(default=False, verbose_name='Kommentare erlaubt'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='allow_comments',
            field=models.BooleanField(default=False, verbose_name='Kommentare erlaubt'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Inhalt'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='is_evaluation',
            field=models.BooleanField(default=False, verbose_name='Abstimmungsauswertung'),
        ),
    ]
