# Generated by Django 3.2.5 on 2022-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_auto_20221208_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='allow_comments',
            field=models.BooleanField(default=False, verbose_name='Kommentare erlaubt'),
        ),
    ]
