# Generated by Django 3.2.5 on 2023-02-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_auto_20230214_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='type',
            field=models.CharField(blank=True, choices=[('falltraining', 'Klausur im Falltraining'), ('exam', 'Examensklausur'), ('original-exam', 'Originalklausur'), ('term-paper', 'Hausarbeit'), ('exercise', 'Übungsfall'), ('tutorial', 'AG-Fall')], max_length=255, verbose_name='Klausurtyp'),
        ),
    ]
