# Generated by Django 3.2.5 on 2023-04-12 06:21

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_color_panel.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_alter_exams_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionpage',
            name='allow_comments',
            field=models.BooleanField(default=False, verbose_name='Kommentare erlaubt'),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar', wagtail.core.blocks.StreamBlock([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts')), ('sidebar_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('color', wagtail_color_panel.blocks.NativeColorBlock('color', default='#333d44')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False))], label='Bild oben, Text darunter')), ('sidebar_calendar_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('calendar', wagtail.core.blocks.DateBlock(format='%Y-%m-%d'))], label='Kalender links, Text rechts')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung')), ('sidebar_subscribe', wagtail.core.blocks.StructBlock([], label='Newsletter-Anmeldung')), ('sidebar_event', wagtail.core.blocks.StructBlock([])), ('sidebar_search', wagtail.core.blocks.StructBlock([], label='Suchfeld'))], label='Seitenleiste', required=False))], verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sidebar',
            field=wagtail.core.fields.StreamField([('sidebar', wagtail.core.blocks.StreamBlock([('sidebar_title', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau unterlegte Überschrift')), ('sidebar_simple', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Schlichter Text')), ('sidebar_border', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock())], label='Grau umrandeter Kasten')), ('sidebar_image_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], label='Bild links, Text rechts')), ('sidebar_header', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('color', wagtail_color_panel.blocks.NativeColorBlock('color', default='#333d44')), ('image', wagtail.images.blocks.ImageChooserBlock()), ('content', wagtail.core.blocks.RichTextBlock(required=False))], label='Bild oben, Text darunter')), ('sidebar_calendar_text', wagtail.core.blocks.StructBlock([('content', wagtail.core.blocks.RichTextBlock()), ('calendar', wagtail.core.blocks.DateBlock(format='%Y-%m-%d'))], label='Kalender links, Text rechts')), ('sidebar_poll', wagtail.core.blocks.StructBlock([('poll', wagtailmodelchooser.blocks.ModelChooserBlock(target_model='wagtailpolls.poll'))], label='Abstimmung')), ('sidebar_subscribe', wagtail.core.blocks.StructBlock([], label='Newsletter-Anmeldung')), ('sidebar_event', wagtail.core.blocks.StructBlock([])), ('sidebar_search', wagtail.core.blocks.StructBlock([], label='Suchfeld'))], label='Seitenleiste', required=False))], verbose_name='Seitenleiste'),
        ),
        migrations.AlterField(
            model_name='jurcoachcarousel',
            name='illustration',
            field=models.CharField(blank=True, choices=[('falltraining', 'Falltraining'), ('wiki', 'Problemfeld-Wiki'), ('mct', 'Multiple-Choice-Test'), ('klausurdatenbank', 'Klausurdatenbank'), ('rechtsprechung', 'Höchstrichterliche Rechtsprechung'), ('tandemklausur', 'Tandemklausur'), ('lernplan', 'Lernplan'), ('reward-system', 'Reward-System')], max_length=255, verbose_name='Auswahl der Illustration'),
        ),
    ]
