# Generated by Django 3.2.5 on 2025-01-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_auto_20230412_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='role',
            field=models.CharField(blank=True, choices=[('chairholder', 'Lehrstuhlinhaber'), ('office-management', 'Office Management'), ('lecturer', 'Lehrbeauftragte'), ('academic-staff-male', 'Wiss. Mitarbeiter'), ('academic-staff-female', 'Wiss. Mitarbeiterin'), ('former academic-staff-male', 'Ehem. Wiss. Mitarbeiter'), ('former academic-staff-female', 'Ehem. Wiss. Mitarbeiterin'), ('academic-assistant', 'Wiss. Hilfskraft'), ('student-assistant', 'Stud. Hilfskraft'), ('jurcoach-law-team-academic', 'Wiss. Hilfskraft Jurcoach'), ('jurcoach-law-team-student', 'Stud. Hilfskraft Jurcoach'), ('jurcoach-evaluation-team', 'Jurcoach Evaluations-Team'), ('jurcoach-web-team', 'Jurcoach Informatik-Team'), ('webmaster', 'Webmaster'), ('associate-professor', 'Privatdozent')], max_length=255, verbose_name='Rolle'),
        ),
        migrations.AlterField(
            model_name='sessionpage',
            name='semester',
            field=models.CharField(blank=True, choices=[('ss-2032', 'Sommersemester 2032'), ('ws-2032', 'Wintersemester 2032/33'), ('ss-2031', 'Sommersemester 2031'), ('ws-2031', 'Wintersemester 2031/32'), ('ss-2030', 'Sommersemester 2030'), ('ws-2030', 'Wintersemester 2030/31'), ('ss-2029', 'Sommersemester 2029'), ('ws-2029', 'Wintersemester 2029/30'), ('ss-2028', 'Sommersemester 2028'), ('ws-2028', 'Wintersemester 2028/29'), ('ss-2027', 'Sommersemester 2027'), ('ws-2027', 'Wintersemester 2027/28'), ('ss-2026', 'Sommersemester 2026'), ('ws-2026', 'Wintersemester 2026/27'), ('ss-2025', 'Sommersemester 2025'), ('ws-2025', 'Wintersemester 2025/26'), ('ss-2024', 'Sommersemester 2024'), ('ws-2024', 'Wintersemester 2024/25'), ('ss-2023', 'Sommersemester 2023'), ('ws-2023', 'Wintersemester 2023/24'), ('ss-2022', 'Sommersemester 2022'), ('ws-2022', 'Wintersemester 2022'), ('ss-2021', 'Sommersemester 2021'), ('ws-2021', 'Wintersemester 2021'), ('ss-2020', 'Sommersemester 2020'), ('ws-2020', 'Wintersemester 2020'), ('ss-2019', 'Sommersemester 2019'), ('ws-2019', 'Wintersemester 2019'), ('ss-2018', 'Sommersemester 2018'), ('ws-2018', 'Sommersemester 2018'), ('ss-2017', 'Sommersemester 2017'), ('ws-2017', 'Wintersemester 2017'), ('ss-2016', 'Sommersemester 2016'), ('ws-2016', 'Wintersemester 2015'), ('ss-2015', 'Sommersemester 2015'), ('ws-2015', 'Wintersemester 2014'), ('ss-2014', 'Sommersemester 2014'), ('ws-2014', 'Wintersemester 2014'), ('ss-2013', 'Sommersemester 2013'), ('ws-2013', 'Wintersemester 2013'), ('ss-2012', 'Sommersemester 2012'), ('ws-2012', 'Wintersemester 2012'), ('ss-2011', 'Sommersemester 2011'), ('ws-2011', 'Wintersemester 2011'), ('ss-2010', 'Sommersemester 2010'), ('ws-2010', 'Wintersemester 2010'), ('ss-2009', 'Sommersemester 2009'), ('ws-2009', 'Wintersemester 2009'), ('ss-2008', 'Sommersemester 2008'), ('ws-2008', 'Wintersemester 2008'), ('ss-2007', 'Sommersemester 2007'), ('ws-2007', 'Wintersemester 2007'), ('ss-2006', 'Sommersemester 2006'), ('ws-2006', 'Wintersemester 2006'), ('ss-2005', 'Sommersemester 2005'), ('ws-2005', 'Wintersemester 2005'), ('ss-2004', 'Sommersemester 2004'), ('ws-2004', 'Wintersemester 2004')], max_length=255, verbose_name='Semesterauswahl'),
        ),
    ]
