# Generated by Django 3.2.5 on 2023-02-20 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tandem_exams', '0002_auto_20230214_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsolution',
            options={'verbose_name': 'Klausurgutachten', 'verbose_name_plural': 'Klausurgutachten'},
        ),
    ]
