# Generated by Django 3.2.5 on 2022-12-01 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0005_alter_urlpath_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('step_type', models.CharField(choices=[('read', 'Read'), ('mark_sections', 'Mark sections'), ('penalities', 'Penalties'), ('problem_areas', 'Problem areas'), ('gap_text', 'Gap text'), ('free_text', 'Free text')], max_length=100)),
                ('config', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Casetraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('shortcase', 'Shortcase'), ('beginner', 'Beginner'), ('advanced', 'Advanced')], max_length=100)),
                ('facts', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseStepProblemArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wiki.article')),
                ('case_step', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_areas', to='casetraining.casestep')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='casestep',
            name='case',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='casetraining.casetraining'),
        ),
        migrations.AlterUniqueTogether(
            name='casestep',
            unique_together={('case', 'position')},
        ),
    ]
