# Generated by Django 3.2.5 on 2022-12-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetraining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestep',
            name='config',
            field=models.TextField(blank=True, null=True),
        ),
    ]
