# Generated by Django 3.2.5 on 2022-11-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetraining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetraining',
            name='facts',
            field=models.TextField(default=''),
        ),
    ]
