# Generated by Django 3.2.5 on 2022-12-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casetraining', '0002_alter_casestep_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestep',
            name='step_type',
            field=models.CharField(choices=[('read', 'Read'), ('mark_sections', 'Mark sections'), ('penalties', 'Penalties'), ('problem_areas', 'Problem areas'), ('gap_text', 'Gap text'), ('free_text', 'Free text')], max_length=100),
        ),
    ]
