# Generated by Django 3.2.5 on 2023-01-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221103_1506'),
        ('casetraining', '0002_alter_casetraining_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetraining',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.submission'),
        ),
    ]
