# Generated by Django 3.2.5 on 2023-01-31 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casetraining', '0004_casetraining_solution_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casetraining',
            options={'verbose_name': 'Falltraining'},
        ),
    ]
