# Generated by Django 3.2.5 on 2022-11-25 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_alter_urlpath_slug'),
        ('flashcards', '0002_auto_20221122_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='wiki_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcard_decks', to='wiki.article'),
        ),
    ]
