# Generated by Django 3.2.5 on 2023-02-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_submission_url'),
        ('flashcards', '0003_alter_deck_wiki_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deck',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.submission'),
        ),
    ]
