# Generated by Django 3.2.5 on 2023-02-02 20:06

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_auto_20230202_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='probability',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='deck',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.deck'),
        ),
    ]
